### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by Dynamo6Dev** [pacely/mailchimp-api-v3#10]
Hi guys, I'm trying to get this wrapper running on my local dev box but when trying your example code from the readme I'm seeing the following error:

Exception in Mailchimp.php line 170:
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Is there any way I can enforce non-ssl or is this a requirement from Mailchimp? Thanks

**Comment by Dynamo6Dev** [comment]
Went through the arduous rigmarole of setting up SSL on my local dev box but the same error still occurred. Finally solved it by opening up the Pacely Mailchimp.php class and replacing

$this->client = new Client( );

with

$this->client = new Client( array('verify' => false) );

in the constructor (line 57 ish). Worked first time. Hope that helps someone

**Comment by ChrisRM** [comment]
Hi @Dynamo6, you really shouldn't disable SSL verification. Instead, have a look here and make sure you place the file in the correct location: http://guzzle.readthedocs.org/en/latest/request-options.html#verify-option
