### ISSUE TITLE
Collection collapse() method throwing an error : array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by Tailzip** [pacely/mailchimp-api-v3#2]
Hello,

When calling the _**/lists/{list_id}**_ resource using the GET method, I'm getting this error :

```
array_merge(): Argument #2 is not an array
```

Line 79, the _**collapse()**_ method is throwing that error :

``` php
return $method == 'get' ? $collection->collapse() : $collection;
```

When I'm just returning **$collection**, it's working. I'm not sure how to fix that?

Thanks for making that library, very helpful! :)

**Comment by ChrisRM** [comment]
Sorry about that, @Tailzip. Should be good now.
