### ISSUE TITLE
Wrong examples

### ISSUE THREAD

**Issue by nschurmann** [pacely/mailchimp-api-v3#28]
This examples are misleading, i'm trying to use it as you explain:
```php
	public function suscribe(Request $request) {
		$result = $MC::request('lists', [
				'fields' => 'lists.id,lists.name,lists.stats.member_count',
				'offset' => 10,
				'count' => 10
		]);
	}
```
Also tried with $mc->request() with no success.  How it is supossed to be used?, and please don't tell me to go to the documentation, i'm coming from there.

**Comment by ChrisRM** [comment]
If you've registered the Facade, you can use it as if it had static methods. E.g `MC::request()`
