### ISSUE TITLE
Getting error while doing composer install

### ISSUE THREAD

**Issue by rkshakya** [pacely/mailchimp-api-v3#3]
Hi Chris,
I have added 
"require": {
        "pacely/mailchimp-apiv3": "dev-master"
    }

to composer.json as 
{
    "name": "pacely/mailchimp-apiv3",
    "description": "Simple API wrapper for Mailchimp API V3",
    "version": "0.1",
    "type": "library",
    "keywords": ["mailchimp", "api", "php", "v3"],
    "license": "MIT",
    "authors": [
        {
            "name": "Chris Magnussen",
            "email": "chris@hirvi.no"
        }
    ],
    "autoload": {
        "psr-4": {
            "Mailchimp\": "src/"
        }
    },
    "require": {
        "php": ">=5.4.0",
        "guzzlehttp/guzzle": "~5.0",
        "illuminate/support": "~5.0"
    },
    "require-dev": {
        "phpspec/phpspec": "~2.2"
    },
    "minimum-stability": "dev",

```
"require": {
    "pacely/mailchimp-apiv3": "dev-master"
}
```

}

When I try to do 
php composer.phar update, it shows an error saying 'The requested package pacely/mailchimp-apiv3 0.1 could not be found.'

Could you please inform what could have gone wrong?
Thanks
![error](https://cloud.githubusercontent.com/assets/1167485/8542172/69506018-24b3-11e5-9103-6b36892fe57c.png)

**Comment by ChrisRM** [comment]
Hi there, @rkshakya. You should create your own `composer.json` file in the root of your project. It doesn't have to contain anything special.

**composer.json**

```
{
    "require": {
        "pacely/mailchimp-apiv3": "dev-master"
    }
}
```

Now, run `composer update` to download the package. The package will be located in your _vendor_ directory. 

To use it, you can do something like this:

```
<?php

require_once 'vendor/autoload.php';

use Mailchimp\Mailchimp;

$mc = new Mailchimp('<api-key>');

$lists = $mc->request('lists', [
    'fields' => 'lists.id,lists.name,lists.stats.member_count',
    'count' => 30
]);

foreach ($lists as $list) {
    echo $list["name"] . " has a total of " . $list["stats"]["member_count"] . " subscribers. <br />";
}
```

**Comment by rkshakya** [comment]
Hi Chris, Thanks a lot for prompt response. Much appreciated.
