### ISSUE TITLE
Pagination does not work on Campaigns

### ISSUE THREAD

**Issue by guerriky** [pacely/mailchimp-api-v3#5]
Hi,
I'm starting to use your package, and the first thing I noticed was that Campaigns (I've yet to try with lists) don't care if I use pagination.

My call looks like this:

```
$res = $mc->get('/campaigns/',array(
    'fields' => 'campaigns.id,campaigns.name',
    'offset' => 10,
    'count' => 20
));
```

But it always return the firts 10 elements.

Am I doing something wrong? 
The same operations work perfectly with subscribers management.

TIA,
Riccardo

**Comment by ChrisRM** [comment]
Your code works perfectly fine here, although campaigns._name_ is not a valid key according to the schema: https://us10.api.mailchimp.com/schema/3.0/Campaigns/Instance.json

``` php
$result = $mc->get('campaigns', [
    'fields' => 'campaigns.id,campaigns.type',
    'offset' => 2,
    'count' => 2
]);

var_dump($result);
```

**Comment by guerriky** [comment]
Hi,
Thanks for your reply.

I took it off now.
Same outcome.

Are there any requirements (other than PHP version) for this to work?

I mean, all the "instance" methods (get list, create subscriber...) work, but it doesn't seem to be the case with "collection" methods.

**Comment by ChrisRM** [comment]
Can you try the `lists` call and see what you get? Try with the _offset_ aswell. 

``` php
$result = $mc->get('lists', [
    'fields' => 'lists.id,lists.name',
    'count' => 10
]);

var_dump($result);
```

**Comment by guerriky** [comment]
Hi,
with both count and offset, I get 9 (from 0 to 8) lists, which are as many as there is on the account.

No filter appears to be applying, and no error message returned.

I'll bypass my firewall and try from there now.

Thanks

**Comment by guerriky** [comment]
Hi,
nope, the firewall was not the issue.

What else could it be?

Thanks

**Comment by ChrisRM** [comment]
I'm not sure to be honest. I haven't experienced any problems with the pagination. You could try one last thing:

``` php
$result = $mc->get('lists?fields=lists.id,lists.name&count=5&offset=4');

var_dump($result);
```

**Comment by guerriky** [comment]
Hi,
darn, that last one just did the trick!

I see exactly what I should now :)

Thanks

**Comment by ChrisRM** [comment]
That's odd. Can you do a `composer update` now and test this call:

```
$result = $mc->get('lists', [
    'fields' => 'lists.id,lists.name',
    'offset' => 4,
    'count' => 5
]);

var_dump($result);
```
