### ISSUE TITLE
Update version at packagist

### ISSUE THREAD

**Issue by ruslan-polutsygan** [pacely/mailchimp-api-v3#6]
Hi

Could you please force update version at packagist https://packagist.org/packages/pacely/mailchimp-apiv3 ?
Composer doesn't see version 1.0.0.

Thanks

**Comment by ChrisRM** [comment]
Packagist aren't picking up the released versions, even though I've done a force-update. I contacted packagist, so hopefully it will be solved quickly.

**Comment by ruslan-polutsygan** [comment]
Great. Thanks.
