### ISSUE TITLE
How can I get data when throw an errors with Laravel 5?

### ISSUE THREAD

**Issue by ALTELMA** [pacely/mailchimp-api-v3#8]
I try to get response through your package, but I can't get response status, detail when data errors. Can you advice me?

**Comment by ChrisRM** [comment]
Not sure what you mean here. If something fails please post a snippet of the code thats failing.

**Comment by ALTELMA** [comment]
Everything is OK, but I don't know how to get result for users. I mean get result from mailchimp.

```
private function makeRequest($resource, $arguments, $method)
    {
        try {
            $options = $this->getOptions($method, $arguments);
            $response = $this->client->{$method}($this->endpoint . $resource, $options);

            $collection = new Collection(
                json_decode($response->getBody())
            );

            if ($collection->count() == 1) {
                return $collection->collapse();
            }

            return $collection;
        } catch (ClientException $e) {
            throw new Exception($e->getResponse()->getBody());
        } catch (RequestException $e) {
            $response = $e->getResponse();

            if ($response instanceof ResponseInterface) {
                throw new Exception($e->getResponse()->getBody());
            }

            throw new Exception($e->getMessage());
        }
    }
```

from this one, It will throw in exception when result not equal 200 or get http error. I prefer to get result although method return an error. I develop on Laravel 5 and when error will display error page instead.

I not sure, you will know what I mean and sorry for my language. If you get it. Can you advice me, please.

**Comment by ChrisRM** [comment]
To catch an exception you should use try-catch:

``` php
try {
    $result = $mc->request('lists', [
        'fields' => 'lists.id,lists.name,lists.stats.member_count',
        'offset' => 10,
        'count' => 10
    ]);
} catch(Exception $e) {
    // Display your error page.
}
```

By doing it this way we are able to control what to do if something fails. If we hadn't done this, you would end up with an exception printed right on screen.

**Comment by ALTELMA** [comment]
I mean like this. And How can I avoid from error page, I send response as json.

![Image of example](http://www.mx7.com/i/d9e/8yaAdE.png)
